storage:
  directory: ${STORAGE_DIRECTORY}
loan-period-days: 28
spring:
  mvc:
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 30MB
  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS library
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: library
    liquibase-schema: library
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: ${AZURE_KEYVAULT_ENDPOINT}
              enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${tenant-id:}/v2.0
          audiences: ${api-client-id:}
  ai:
    openai:
      api-key: ${openai-api-key}
      chat:
        options:
          model: gpt-5
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /api
management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
